@startuml

actor User
participant "System" as POS
User -> POS: signUp()
User -> POS: signIn(username, password)
User -> POS: bookSearch(bookTitle)
POS --> User: Display matching results
User -> POS: borrowBook(bookTitle, bookID)
POS --> User: markAsBorrowed
POS --> User: Display "borrowed successfully"
User -> POS: returnBook(bookTitle, bookID)
POS --> User: markAsReturned
POS --> User: Display "returned successfully"
@enduml


